modLoader="javafml"
loaderVersion="[38,)"
issueTrackerURL="https://github.com/Vazkii/AutoRegLib"
license="https://github.com/Vazkii/AutoRegLib/blob/master/README.md"

[[mods]]
modId="autoreglib"
displayName="AutoRegLib"
version="${file.jarVersion}"
authors="Vazkii"
description='''Automatically item, block, and model registration for mods.'''
